[toolchain]
anchor_version = "0.29.0"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_clusters_initiator = "eDawZydN4oExTTkLpvRYFGSj7xVpdRHfwrQUp2LDjRd"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.devnet.solana.com"
# cluster = "localnet"
wallet = "./keypairs/deployer.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
